from flask import Blueprint, jsonify

recipe_blueprint = Blueprint('recipe', __name__)


@recipe_blueprint.route('/api/json/v1/recipe/<id>', methods=['GET'])
def get_recipe_id(id):
    if id == '52874':
        meals = [
            {
                "idMeal": "52874",
                "strMeal": "Beef and Mustard Pie",
                "strDrinkAlternate": "null",
                "strCategory": "Beef",
                "strArea": "British",
                "strInstructions": "Preheat the oven to 150C/300F/Gas 2.\r\nToss the beef and flour together in a bowl with some salt and black pepper.\r\nHeat a large casserole until hot, add half of the rapeseed oil and enough of the beef to just cover the bottom of the casserole.\r\nFry until browned on each side, then remove and set aside. Repeat with the remaining oil and beef.\r\nReturn the beef to the pan, add the wine and cook until the volume of liquid has reduced by half, then add the stock, onion, carrots, thyme and mustard, and season well with salt and pepper.\r\nCover with a lid and place in the oven for two hours.\r\nRemove from the oven, check the seasoning and set aside to cool. Remove the thyme.\r\nWhen the beef is cool and you're ready to assemble the pie, preheat the oven to 200C/400F/Gas 6.\r\nTransfer the beef to a pie dish, brush the rim with the beaten egg yolks and lay the pastry over the top. Brush the top of the pastry with more beaten egg.\r\nTrim the pastry so there is just enough excess to crimp the edges, then place in the oven and bake for 30 minutes, or until the pastry is golden-brown and cooked through.\r\nFor the green beans, bring a saucepan of salted water to the boil, add the beans and cook for 4-5 minutes, or until just tender.\r\nDrain and toss with the butter, then season with black pepper.\r\nTo serve, place a large spoonful of pie onto each plate with some green beans alongside.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg",
                "strTags": "Meat,Pie",
                "strYoutube": "https://www.youtube.com/watch?v=nMyBC9staMU",
                "strIngredient1": "Beef",
                "strIngredient2": "Plain Flour",
                "strIngredient3": "Rapeseed Oil",
                "strIngredient4": "Red Wine",
                "strIngredient5": "Beef Stock",
                "strIngredient6": "Onion",
                "strIngredient7": "Carrots",
                "strIngredient8": "Thyme",
                "strIngredient9": "Mustard",
                "strIngredient10": "Egg Yolks",
                "strIngredient11": "Puff Pastry",
                "strIngredient12": "Green Beans",
                "strIngredient13": "Butter",
                "strIngredient14": "Salt",
                "strIngredient15": "Pepper",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "1kg",
                "strMeasure2": "2 tbs",
                "strMeasure3": "2 tbs",
                "strMeasure4": "200ml",
                "strMeasure5": "400ml",
                "strMeasure6": "1 finely sliced",
                "strMeasure7": "2 chopped",
                "strMeasure8": "3 sprigs",
                "strMeasure9": "2 tbs",
                "strMeasure10": "2 free-range",
                "strMeasure11": "400g",
                "strMeasure12": "300g",
                "strMeasure13": "25g",
                "strMeasure14": "pinch",
                "strMeasure15": "pinch",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "https://www.bbc.co.uk/food/recipes/beef_and_mustard_pie_58002",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '52878':
        meals = [
            {
                "idMeal": "52878",
                "strMeal": "Beef and Oyster pie",
                "strDrinkAlternate": "null",
                "strCategory": "Beef",
                "strArea": "British",
                "strInstructions": "Season the beef cubes with salt and black pepper. Heat a tablespoon of oil in the frying pan and fry the meat over a high heat. Do this in three batches so that you don’t overcrowd the pan, transferring the meat to a large flameproof casserole dish once it is browned all over. Add extra oil if the pan seems dry.\r\nIn the same pan, add another tablespoon of oil and cook the shallots for 4-5 minutes, then add the garlic and fry for 30 seconds. Add the bacon and fry until slightly browned. Transfer the onion and bacon mixture to the casserole dish and add the herbs.\r\nPreheat the oven to 180C/350F/Gas 4.\r\nPour the stout into the frying pan and bring to the boil, stirring to lift any stuck-on browned bits from the bottom of the pan. Pour the stout over the beef in the casserole dish and add the stock. Cover the casserole and place it in the oven for 1½-2 hours, or until the beef is tender and the sauce is reduced.\r\nSkim off any surface fat, taste and add salt and pepper if necessary, then stir in the cornflour paste. Put the casserole dish on the hob – don’t forget that it will be hot – and simmer for 1-2 minutes, stirring, until thickened. Leave to cool.\r\nIncrease the oven to 200C/400F/Gas 6. To make the pastry, put the flour and salt in a very large bowl. Grate the butter and stir it into the flour in three batches. Gradually add 325ml/11fl oz cold water – you may not need it all – and stir with a round-bladed knife until the mixture just comes together. Knead the pastry lightly into a ball on a lightly floured surface and set aside 250g/9oz for the pie lid.\r\nRoll the rest of the pastry out until about 2cm/¾in larger than the dish you’re using. Line the dish with the pastry then pile in the filling, tucking the oysters in as well. Brush the edge of the pastry with beaten egg.\r\nRoll the remaining pastry until slightly larger than your dish and gently lift over the filling, pressing the edges firmly to seal, then trim with a sharp knife. Brush with beaten egg to glaze. Put the dish on a baking tray and bake for 25-30 minutes, or until the pastry is golden-brown and the filling is bubbling.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg",
                "strTags": "Pie",
                "strYoutube": "https://www.youtube.com/watch?v=ONX74yP6JnI",
                "strIngredient1": "Beef",
                "strIngredient2": "Olive Oil",
                "strIngredient3": "Shallots",
                "strIngredient4": "Garlic",
                "strIngredient5": "Bacon",
                "strIngredient6": "Thyme",
                "strIngredient7": "Bay Leaf",
                "strIngredient8": "Stout",
                "strIngredient9": "Beef Stock",
                "strIngredient10": "Corn Flour",
                "strIngredient11": "Oysters",
                "strIngredient12": "Plain Flour",
                "strIngredient13": "Salt",
                "strIngredient14": "Butter",
                "strIngredient15": "Eggs",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "900g",
                "strMeasure2": "3 tbs",
                "strMeasure3": "3",
                "strMeasure4": "2 cloves minced",
                "strMeasure5": "125g",
                "strMeasure6": "1 tbs chopped",
                "strMeasure7": "2",
                "strMeasure8": "330ml",
                "strMeasure9": "400ml",
                "strMeasure10": "2 tbs",
                "strMeasure11": "8",
                "strMeasure12": "400g",
                "strMeasure13": "pinch",
                "strMeasure14": "250g",
                "strMeasure15": "To Glaze",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "https://www.bbc.co.uk/food/recipes/beef_and_oyster_pie_65230",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '53071':
        meals = [
            {
                "idMeal": "53071",
                "strMeal": "Beef Asado",
                "strDrinkAlternate": "null",
                "strCategory": "Beef",
                "strArea": "Filipino",
                "strInstructions": "0.\tCombine beef, crushed peppercorn, soy sauce, vinegar, dried bay leaves, lemon, and tomato sauce. Mix well. Marinate beef for at least 30 minutes.\r\n1.\tPut the marinated beef in a cooking pot along with remaining marinade. Add water. Let boil.\r\n2.\tAdd Knorr Beef Cube. Stir. Cover the pot and cook for 40 minutes in low heat.\r\n3.\tTurn the beef over. Add tomato paste. Continue cooking until beef tenderizes. Set aside.\r\n4.\tHeat oil in a pan. Fry the potato until it browns. Turn over and continue frying the opposite side. Remove from the pan and place on a clean plate. Do the same with the carrots.\r\n5.\tSave 3 tablespoons of cooking oil from the pan where the potato was fried. Saute onion and garlic until onion softens.\r\n6.\tPour-in the sauce from the beef stew. Let boil. Add the beef. Cook for 2 minutes.\r\n7.\tAdd butter and let it melt. Continue cooking until the sauce reduces to half.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/pkopc31683207947.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=lNlK8DVhXXA",
                "strIngredient1": "Beef",
                "strIngredient2": "Beef Stock Concentrate",
                "strIngredient3": "Tomato Puree",
                "strIngredient4": "Water",
                "strIngredient5": "Soy Sauce",
                "strIngredient6": "White Wine Vinegar",
                "strIngredient7": "Pepper",
                "strIngredient8": "Bay Leaf",
                "strIngredient9": "Lemon",
                "strIngredient10": "Tomato Sauce",
                "strIngredient11": "Butter",
                "strIngredient12": "Olive Oil",
                "strIngredient13": "Onion",
                "strIngredient14": "Garlic",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "1.5kg",
                "strMeasure2": "1",
                "strMeasure3": "8 ounces",
                "strMeasure4": "3 cups ",
                "strMeasure5": "6 tablespoons",
                "strMeasure6": "1 tbs",
                "strMeasure7": "2 tbs",
                "strMeasure8": "4",
                "strMeasure9": "1/2 ",
                "strMeasure10": "2 tbs",
                "strMeasure11": "3 tbs",
                "strMeasure12": "1/2 cup ",
                "strMeasure13": "1 chopped",
                "strMeasure14": "4 cloves",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "https://panlasangpinoy.com/beef-asado/",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '53050':
        meals = [
            {
                "idMeal": "53050",
                "strMeal": "Ayam Percik",
                "strDrinkAlternate": "null",
                "strCategory": "Chicken",
                "strArea": "Malaysian",
                "strInstructions": "In a blender, add the ingredients for the spice paste and blend until smooth.\r\nOver medium heat, pour the spice paste in a skillet or pan and fry for 10 minutes until fragrant. Add water or oil 1 tablespoon at a time if the paste becomes too dry. Don't burn the paste. Lower the fire slightly if needed.\r\nAdd the cloves, cardamom, tamarind pulp, coconut milk, water, sugar and salt. Turn the heat up and bring the mixture to boil. Turn the heat to medium low and simmer for 10 minutes. Stir occasionally. It will reduce slightly. This is the marinade/sauce, so taste and adjust seasoning if necessary. Don't worry if it's slightly bitter. It will go away when roasting.\r\nWhen the marinade/sauce has cooled, pour everything over the chicken and marinate overnight to two days.\r\nPreheat the oven to 425 F.\r\nRemove the chicken from the marinade. Spoon the marinade onto a greased (or aluminum lined) baking sheet. Lay the chicken on top of the sauce (make sure the chicken covers the sauce and the sauce isn't exposed or it'll burn) and spread the remaining marinade on the chicken. Roast for 35-45 minutes or until internal temp of the thickest part of chicken is at least 175 F.\r\nLet chicken rest for 5 minutes. Brush the chicken with some of the oil. Serve chicken with the sauce over steamed rice (or coconut rice).",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/020z181619788503.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=9ytR28QK6I8",
                "strIngredient1": "Chicken Thighs",
                "strIngredient2": "Challots",
                "strIngredient3": "Ginger",
                "strIngredient4": "Garlic Clove",
                "strIngredient5": "Cayenne Pepper",
                "strIngredient6": "Turmeric",
                "strIngredient7": "Cumin",
                "strIngredient8": "Coriander",
                "strIngredient9": "Fennel",
                "strIngredient10": "Tamarind Paste",
                "strIngredient11": "Coconut Milk",
                "strIngredient12": "Sugar",
                "strIngredient13": "Water",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "6",
                "strMeasure2": "16",
                "strMeasure3": "1 1/2 ",
                "strMeasure4": "6",
                "strMeasure5": "8",
                "strMeasure6": "2 tbs",
                "strMeasure7": "1 1/2 ",
                "strMeasure8": "1 1/2 ",
                "strMeasure9": "1 1/2 ",
                "strMeasure10": "2 tbs",
                "strMeasure11": "1 can ",
                "strMeasure12": "1 tsp ",
                "strMeasure13": "1 cup ",
                "strMeasure14": " ",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "http://www.curiousnut.com/roasted-spiced-chicken-ayam-percik/",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '53049':
        meals = [
            {
                "idMeal": "53049",
                "strMeal": "Apam balik",
                "strDrinkAlternate": "null",
                "strCategory": "Dessert",
                "strArea": "Malaysian",
                "strInstructions": "Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.\r\n\r\nSpread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.\r\n\r\nAdd butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.\r\n\r\nCut into wedges and best eaten when it is warm.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=6R8ffRRJcrg",
                "strIngredient1": "Milk",
                "strIngredient2": "Oil",
                "strIngredient3": "Eggs",
                "strIngredient4": "Flour",
                "strIngredient5": "Baking Powder",
                "strIngredient6": "Salt",
                "strIngredient7": "Unsalted Butter",
                "strIngredient8": "Sugar",
                "strIngredient9": "Peanut Butter",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "200ml",
                "strMeasure2": "60ml",
                "strMeasure3": "2",
                "strMeasure4": "1600g",
                "strMeasure5": "3 tsp",
                "strMeasure6": "1/2 tsp",
                "strMeasure7": "25g",
                "strMeasure8": "45g",
                "strMeasure9": "3 tbs",
                "strMeasure10": " ",
                "strMeasure11": " ",
                "strMeasure12": " ",
                "strMeasure13": " ",
                "strMeasure14": " ",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "https://www.nyonyacooking.com/recipes/apam-balik~SJ5WuvsDf9WQ",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    else:
        return jsonify({"message": "Recipe not found"})

    return jsonify({"meals": meals})
