from flask import Blueprint, jsonify

recipe_blueprint = Blueprint('recipe', __name__)


@recipe_blueprint.route('/api/json/v1/recipe/<id>', methods=['GET'])
def get_recipe_id(id):
    if id == '1001':
        meals = [
            {
                "idMeal": "1001",
                "strMeal": "Beef and Mustard Pie",
                "strDrinkAlternate": "null",
                "strCategory": "Kentang",
                "strArea": "British",
                "strInstructions": "Preheat the oven to 150C/300F/Gas 2.\r\nToss the beef and flour together in a bowl with some salt and black pepper.\r\nHeat a large casserole until hot, add half of the rapeseed oil and enough of the beef to just cover the bottom of the casserole.\r\nFry until browned on each side, then remove and set aside. Repeat with the remaining oil and beef.\r\nReturn the beef to the pan, add the wine and cook until the volume of liquid has reduced by half, then add the stock, onion, carrots, thyme and mustard, and season well with salt and pepper.\r\nCover with a lid and place in the oven for two hours.\r\nRemove from the oven, check the seasoning and set aside to cool. Remove the thyme.\r\nWhen the beef is cool and you're ready to assemble the pie, preheat the oven to 200C/400F/Gas 6.\r\nTransfer the beef to a pie dish, brush the rim with the beaten egg yolks and lay the pastry over the top. Brush the top of the pastry with more beaten egg.\r\nTrim the pastry so there is just enough excess to crimp the edges, then place in the oven and bake for 30 minutes, or until the pastry is golden-brown and cooked through.\r\nFor the green beans, bring a saucepan of salted water to the boil, add the beans and cook for 4-5 minutes, or until just tender.\r\nDrain and toss with the butter, then season with black pepper.\r\nTo serve, place a large spoonful of pie onto each plate with some green beans alongside.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg",
                "strTags": "Meat,Pie",
                "strYoutube": "https://www.youtube.com/watch?v=nMyBC9staMU",
                "strIngredient1": "Beef",
                "strIngredient2": "Plain Flour",
                "strIngredient3": "Rapeseed Oil",
                "strIngredient4": "Red Wine",
                "strIngredient5": "Beef Stock",
                "strIngredient6": "Onion",
                "strIngredient7": "Carrots",
                "strIngredient8": "Thyme",
                "strIngredient9": "Mustard",
                "strIngredient10": "Egg Yolks",
                "strIngredient11": "Puff Pastry",
                "strIngredient12": "Green Beans",
                "strIngredient13": "Butter",
                "strIngredient14": "Salt",
                "strIngredient15": "Pepper",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "1kg",
                "strMeasure2": "2 tbs",
                "strMeasure3": "2 tbs",
                "strMeasure4": "200ml",
                "strMeasure5": "400ml",
                "strMeasure6": "1 finely sliced",
                "strMeasure7": "2 chopped",
                "strMeasure8": "3 sprigs",
                "strMeasure9": "2 tbs",
                "strMeasure10": "2 free-range",
                "strMeasure11": "400g",
                "strMeasure12": "300g",
                "strMeasure13": "25g",
                "strMeasure14": "pinch",
                "strMeasure15": "pinch",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "https://www.bbc.co.uk/food/recipes/beef_and_mustard_pie_58002",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1002':
        meals = [
            {
                "idMeal": "1002",
                "strMeal": "Beef and Oyster pie",
                "strDrinkAlternate": "null",
                "strCategory": "Kentang",
                "strArea": "British",
                "strInstructions": "Season the beef cubes with salt and black pepper. Heat a tablespoon of oil in the frying pan and fry the meat over a high heat. Do this in three batches so that you don’t overcrowd the pan, transferring the meat to a large flameproof casserole dish once it is browned all over. Add extra oil if the pan seems dry.\r\nIn the same pan, add another tablespoon of oil and cook the shallots for 4-5 minutes, then add the garlic and fry for 30 seconds. Add the bacon and fry until slightly browned. Transfer the onion and bacon mixture to the casserole dish and add the herbs.\r\nPreheat the oven to 180C/350F/Gas 4.\r\nPour the stout into the frying pan and bring to the boil, stirring to lift any stuck-on browned bits from the bottom of the pan. Pour the stout over the beef in the casserole dish and add the stock. Cover the casserole and place it in the oven for 1½-2 hours, or until the beef is tender and the sauce is reduced.\r\nSkim off any surface fat, taste and add salt and pepper if necessary, then stir in the cornflour paste. Put the casserole dish on the hob – don’t forget that it will be hot – and simmer for 1-2 minutes, stirring, until thickened. Leave to cool.\r\nIncrease the oven to 200C/400F/Gas 6. To make the pastry, put the flour and salt in a very large bowl. Grate the butter and stir it into the flour in three batches. Gradually add 325ml/11fl oz cold water – you may not need it all – and stir with a round-bladed knife until the mixture just comes together. Knead the pastry lightly into a ball on a lightly floured surface and set aside 250g/9oz for the pie lid.\r\nRoll the rest of the pastry out until about 2cm/¾in larger than the dish you’re using. Line the dish with the pastry then pile in the filling, tucking the oysters in as well. Brush the edge of the pastry with beaten egg.\r\nRoll the remaining pastry until slightly larger than your dish and gently lift over the filling, pressing the edges firmly to seal, then trim with a sharp knife. Brush with beaten egg to glaze. Put the dish on a baking tray and bake for 25-30 minutes, or until the pastry is golden-brown and the filling is bubbling.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg",
                "strTags": "Pie",
                "strYoutube": "https://www.youtube.com/watch?v=ONX74yP6JnI",
                "strIngredient1": "Beef",
                "strIngredient2": "Olive Oil",
                "strIngredient3": "Shallots",
                "strIngredient4": "Garlic",
                "strIngredient5": "Bacon",
                "strIngredient6": "Thyme",
                "strIngredient7": "Bay Leaf",
                "strIngredient8": "Stout",
                "strIngredient9": "Beef Stock",
                "strIngredient10": "Corn Flour",
                "strIngredient11": "Oysters",
                "strIngredient12": "Plain Flour",
                "strIngredient13": "Salt",
                "strIngredient14": "Butter",
                "strIngredient15": "Eggs",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "900g",
                "strMeasure2": "3 tbs",
                "strMeasure3": "3",
                "strMeasure4": "2 cloves minced",
                "strMeasure5": "125g",
                "strMeasure6": "1 tbs chopped",
                "strMeasure7": "2",
                "strMeasure8": "330ml",
                "strMeasure9": "400ml",
                "strMeasure10": "2 tbs",
                "strMeasure11": "8",
                "strMeasure12": "400g",
                "strMeasure13": "pinch",
                "strMeasure14": "250g",
                "strMeasure15": "To Glaze",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "https://www.bbc.co.uk/food/recipes/beef_and_oyster_pie_65230",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1003':
        meals = [
            {
                "idMeal": "1003",
                "strMeal": "Beef Asado",
                "strDrinkAlternate": "null",
                "strCategory": "Kentang",
                "strArea": "Filipino",
                "strInstructions": "0.\tCombine beef, crushed peppercorn, soy sauce, vinegar, dried bay leaves, lemon, and tomato sauce. Mix well. Marinate beef for at least 30 minutes.\r\n1.\tPut the marinated beef in a cooking pot along with remaining marinade. Add water. Let boil.\r\n2.\tAdd Knorr Beef Cube. Stir. Cover the pot and cook for 40 minutes in low heat.\r\n3.\tTurn the beef over. Add tomato paste. Continue cooking until beef tenderizes. Set aside.\r\n4.\tHeat oil in a pan. Fry the potato until it browns. Turn over and continue frying the opposite side. Remove from the pan and place on a clean plate. Do the same with the carrots.\r\n5.\tSave 3 tablespoons of cooking oil from the pan where the potato was fried. Saute onion and garlic until onion softens.\r\n6.\tPour-in the sauce from the beef stew. Let boil. Add the beef. Cook for 2 minutes.\r\n7.\tAdd butter and let it melt. Continue cooking until the sauce reduces to half.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/pkopc31683207947.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=lNlK8DVhXXA",
                "strIngredient1": "Beef",
                "strIngredient2": "Beef Stock Concentrate",
                "strIngredient3": "Tomato Puree",
                "strIngredient4": "Water",
                "strIngredient5": "Soy Sauce",
                "strIngredient6": "White Wine Vinegar",
                "strIngredient7": "Pepper",
                "strIngredient8": "Bay Leaf",
                "strIngredient9": "Lemon",
                "strIngredient10": "Tomato Sauce",
                "strIngredient11": "Butter",
                "strIngredient12": "Olive Oil",
                "strIngredient13": "Onion",
                "strIngredient14": "Garlic",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "1.5kg",
                "strMeasure2": "1",
                "strMeasure3": "8 ounces",
                "strMeasure4": "3 cups ",
                "strMeasure5": "6 tablespoons",
                "strMeasure6": "1 tbs",
                "strMeasure7": "2 tbs",
                "strMeasure8": "4",
                "strMeasure9": "1/2 ",
                "strMeasure10": "2 tbs",
                "strMeasure11": "3 tbs",
                "strMeasure12": "1/2 cup ",
                "strMeasure13": "1 chopped",
                "strMeasure14": "4 cloves",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "https://panlasangpinoy.com/beef-asado/",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '2001':
        meals = [
            {
                "idMeal": "2001",
                "strMeal": "Ayam Percik",
                "strDrinkAlternate": "null",
                "strCategory": "Kembang Kol",
                "strArea": "Malaysian",
                "strInstructions": "In a blender, add the ingredients for the spice paste and blend until smooth.\r\nOver medium heat, pour the spice paste in a skillet or pan and fry for 10 minutes until fragrant. Add water or oil 1 tablespoon at a time if the paste becomes too dry. Don't burn the paste. Lower the fire slightly if needed.\r\nAdd the cloves, cardamom, tamarind pulp, coconut milk, water, sugar and salt. Turn the heat up and bring the mixture to boil. Turn the heat to medium low and simmer for 10 minutes. Stir occasionally. It will reduce slightly. This is the marinade/sauce, so taste and adjust seasoning if necessary. Don't worry if it's slightly bitter. It will go away when roasting.\r\nWhen the marinade/sauce has cooled, pour everything over the chicken and marinate overnight to two days.\r\nPreheat the oven to 425 F.\r\nRemove the chicken from the marinade. Spoon the marinade onto a greased (or aluminum lined) baking sheet. Lay the chicken on top of the sauce (make sure the chicken covers the sauce and the sauce isn't exposed or it'll burn) and spread the remaining marinade on the chicken. Roast for 35-45 minutes or until internal temp of the thickest part of chicken is at least 175 F.\r\nLet chicken rest for 5 minutes. Brush the chicken with some of the oil. Serve chicken with the sauce over steamed rice (or coconut rice).",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/020z181619788503.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=9ytR28QK6I8",
                "strIngredient1": "Chicken Thighs",
                "strIngredient2": "Challots",
                "strIngredient3": "Ginger",
                "strIngredient4": "Garlic Clove",
                "strIngredient5": "Cayenne Pepper",
                "strIngredient6": "Turmeric",
                "strIngredient7": "Cumin",
                "strIngredient8": "Coriander",
                "strIngredient9": "Fennel",
                "strIngredient10": "Tamarind Paste",
                "strIngredient11": "Coconut Milk",
                "strIngredient12": "Sugar",
                "strIngredient13": "Water",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "6",
                "strMeasure2": "16",
                "strMeasure3": "1 1/2 ",
                "strMeasure4": "6",
                "strMeasure5": "8",
                "strMeasure6": "2 tbs",
                "strMeasure7": "1 1/2 ",
                "strMeasure8": "1 1/2 ",
                "strMeasure9": "1 1/2 ",
                "strMeasure10": "2 tbs",
                "strMeasure11": "1 can ",
                "strMeasure12": "1 tsp ",
                "strMeasure13": "1 cup ",
                "strMeasure14": " ",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "http://www.curiousnut.com/roasted-spiced-chicken-ayam-percik/",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '3001':
        meals = [
            {
                "idMeal": "3001",
                "strMeal": "Tumis Brokoli Bawang Putih",
                "strDrinkAlternate": "null",
                "strCategory": "Kubis",
                "strArea": "Indonesia",
                "strInstructions": "Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.\r\n\r\nSpread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.\r\n\r\nAdd butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.\r\n\r\nCut into wedges and best eaten when it is warm.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=_2x5d4B9-Ko",
                "strIngredient1": "Brokoli",
                "strIngredient2": "Saus Tiram",
                "strIngredient3": "Bawang Putih",
                "strIngredient4": "Kaldu Jamur",
                "strIngredient5": "Garam",
                "strIngredient6": "Gula",
                "strIngredient7": "Lada Putih Bubuk",
                "strIngredient8": "",
                "strIngredient9": "",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 buah",
                "strMeasure2": "1 sendok makan",
                "strMeasure3": "3-4 siung",
                "strMeasure4": "1 sendok teh",
                "strMeasure5": "1 jumput",
                "strMeasure6": "1 sendok teh",
                "strMeasure7": "1/2 sendok teh",
                "strMeasure8": "",
                "strMeasure9": "",
                "strMeasure10": " ",
                "strMeasure11": " ",
                "strMeasure12": " ",
                "strMeasure13": " ",
                "strMeasure14": " ",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "https://youtu.be/_2x5d4B9-Ko?si=BKnocOMOjEo0W9NT",
                "strImageSource": "null",
                "strKal": "54",
                "strLemak": "2,69g",
                "strKarb": "6,98g",
                "strProt": "2,3g",
                "strSourceGizi": "https://www.fatsecret.co.id/kalori-gizi/umum/brokoli-dimasak-(dari-segar)",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '4001':
        meals = [
            {
                "idMeal": "4001",
                "strMeal": "Ayam Percik",
                "strDrinkAlternate": "null",
                "strCategory": "Labu",
                "strArea": "Indonesia",
                "strInstructions": "Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.\r\n\r\nSpread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.\r\n\r\nAdd butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.\r\n\r\nCut into wedges and best eaten when it is warm.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=_2x5d4B9-Ko",
                "strIngredient1": "Brokoli",
                "strIngredient2": "Saus Tiram",
                "strIngredient3": "Bawang Putih",
                "strIngredient4": "Kaldu Jamur",
                "strIngredient5": "Garam",
                "strIngredient6": "Gula",
                "strIngredient7": "Lada Putih Bubuk",
                "strIngredient8": "",
                "strIngredient9": "",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 buah",
                "strMeasure2": "1 sendok makan",
                "strMeasure3": "3-4 siung",
                "strMeasure4": "1 sendok teh",
                "strMeasure5": "1 jumput",
                "strMeasure6": "1 sendok teh",
                "strMeasure7": "1/2 sendok teh",
                "strMeasure8": "",
                "strMeasure9": "",
                "strMeasure10": " ",
                "strMeasure11": " ",
                "strMeasure12": " ",
                "strMeasure13": " ",
                "strMeasure14": " ",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "https://youtu.be/_2x5d4B9-Ko?si=BKnocOMOjEo0W9NT",
                "strImageSource": "null",
                "strKal": "54",
                "strLemak": "2,69g",
                "strKarb": "6,98g",
                "strProt": "2,3g",
                "strSourceGizi": "https://www.fatsecret.co.id/kalori-gizi/umum/brokoli-dimasak-(dari-segar)",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '5001':
        meals = [
            {
                "idMeal": "5001",
                "strMeal": "Tumis Brokoli Bawang Putih",
                "strDrinkAlternate": "null",
                "strCategory": "Paprika",
                "strArea": "Indonesia",
                "strInstructions": "Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.\r\n\r\nSpread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.\r\n\r\nAdd butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.\r\n\r\nCut into wedges and best eaten when it is warm.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=_2x5d4B9-Ko",
                "strIngredient1": "Brokoli",
                "strIngredient2": "Saus Tiram",
                "strIngredient3": "Bawang Putih",
                "strIngredient4": "Kaldu Jamur",
                "strIngredient5": "Garam",
                "strIngredient6": "Gula",
                "strIngredient7": "Lada Putih Bubuk",
                "strIngredient8": "",
                "strIngredient9": "",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 buah",
                "strMeasure2": "1 sendok makan",
                "strMeasure3": "3-4 siung",
                "strMeasure4": "1 sendok teh",
                "strMeasure5": "1 jumput",
                "strMeasure6": "1 sendok teh",
                "strMeasure7": "1/2 sendok teh",
                "strMeasure8": "",
                "strMeasure9": "",
                "strMeasure10": " ",
                "strMeasure11": " ",
                "strMeasure12": " ",
                "strMeasure13": " ",
                "strMeasure14": " ",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "https://youtu.be/_2x5d4B9-Ko?si=BKnocOMOjEo0W9NT",
                "strImageSource": "null",
                "strKal": "54",
                "strLemak": "2,69g",
                "strKarb": "6,98g",
                "strProt": "2,3g",
                "strSourceGizi": "https://www.fatsecret.co.id/kalori-gizi/umum/brokoli-dimasak-(dari-segar)",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '6001':
        meals = [
            {
                "idMeal": "6001",
                "strMeal": "Ayam Percik",
                "strDrinkAlternate": "null",
                "strCategory": "Timun",
                "strArea": "Indonesia",
                "strInstructions": "Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.\r\n\r\nSpread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.\r\n\r\nAdd butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.\r\n\r\nCut into wedges and best eaten when it is warm.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=_2x5d4B9-Ko",
                "strIngredient1": "Brokoli",
                "strIngredient2": "Saus Tiram",
                "strIngredient3": "Bawang Putih",
                "strIngredient4": "Kaldu Jamur",
                "strIngredient5": "Garam",
                "strIngredient6": "Gula",
                "strIngredient7": "Lada Putih Bubuk",
                "strIngredient8": "",
                "strIngredient9": "",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 buah",
                "strMeasure2": "1 sendok makan",
                "strMeasure3": "3-4 siung",
                "strMeasure4": "1 sendok teh",
                "strMeasure5": "1 jumput",
                "strMeasure6": "1 sendok teh",
                "strMeasure7": "1/2 sendok teh",
                "strMeasure8": "",
                "strMeasure9": "",
                "strMeasure10": " ",
                "strMeasure11": " ",
                "strMeasure12": " ",
                "strMeasure13": " ",
                "strMeasure14": " ",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "https://youtu.be/_2x5d4B9-Ko?si=BKnocOMOjEo0W9NT",
                "strImageSource": "null",
                "strKal": "54",
                "strLemak": "2,69g",
                "strKarb": "6,98g",
                "strProt": "2,3g",
                "strSourceGizi": "https://www.fatsecret.co.id/kalori-gizi/umum/brokoli-dimasak-(dari-segar)",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '7001':
        meals = [
            {
                "idMeal": "7001",
                "strMeal": "Tumis Brokoli Bawang Putih",
                "strDrinkAlternate": "null",
                "strCategory": "Tomat",
                "strArea": "Indonesia",
                "strInstructions": "Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.\r\n\r\nSpread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.\r\n\r\nAdd butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.\r\n\r\nCut into wedges and best eaten when it is warm.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=_2x5d4B9-Ko",
                "strIngredient1": "Brokoli",
                "strIngredient2": "Saus Tiram",
                "strIngredient3": "Bawang Putih",
                "strIngredient4": "Kaldu Jamur",
                "strIngredient5": "Garam",
                "strIngredient6": "Gula",
                "strIngredient7": "Lada Putih Bubuk",
                "strIngredient8": "",
                "strIngredient9": "",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 buah",
                "strMeasure2": "1 sendok makan",
                "strMeasure3": "3-4 siung",
                "strMeasure4": "1 sendok teh",
                "strMeasure5": "1 jumput",
                "strMeasure6": "1 sendok teh",
                "strMeasure7": "1/2 sendok teh",
                "strMeasure8": "",
                "strMeasure9": "",
                "strMeasure10": " ",
                "strMeasure11": " ",
                "strMeasure12": " ",
                "strMeasure13": " ",
                "strMeasure14": " ",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "https://youtu.be/_2x5d4B9-Ko?si=BKnocOMOjEo0W9NT",
                "strImageSource": "null",
                "strKal": "54",
                "strLemak": "2,69g",
                "strKarb": "6,98g",
                "strProt": "2,3g",
                "strSourceGizi": "https://www.fatsecret.co.id/kalori-gizi/umum/brokoli-dimasak-(dari-segar)",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '8001':
        meals = [
            {
                "idMeal": "8001",
                "strMeal": "Ayam Percik",
                "strDrinkAlternate": "null",
                "strCategory": "Wortel",
                "strArea": "Indonesia",
                "strInstructions": "Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.\r\n\r\nSpread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.\r\n\r\nAdd butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.\r\n\r\nCut into wedges and best eaten when it is warm.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=_2x5d4B9-Ko",
                "strIngredient1": "Brokoli",
                "strIngredient2": "Saus Tiram",
                "strIngredient3": "Bawang Putih",
                "strIngredient4": "Kaldu Jamur",
                "strIngredient5": "Garam",
                "strIngredient6": "Gula",
                "strIngredient7": "Lada Putih Bubuk",
                "strIngredient8": "",
                "strIngredient9": "",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 buah",
                "strMeasure2": "1 sendok makan",
                "strMeasure3": "3-4 siung",
                "strMeasure4": "1 sendok teh",
                "strMeasure5": "1 jumput",
                "strMeasure6": "1 sendok teh",
                "strMeasure7": "1/2 sendok teh",
                "strMeasure8": "",
                "strMeasure9": "",
                "strMeasure10": " ",
                "strMeasure11": " ",
                "strMeasure12": " ",
                "strMeasure13": " ",
                "strMeasure14": " ",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "https://youtu.be/_2x5d4B9-Ko?si=BKnocOMOjEo0W9NT",
                "strImageSource": "null",
                "strKal": "54",
                "strLemak": "2,69g",
                "strKarb": "6,98g",
                "strProt": "2,3g",
                "strSourceGizi": "https://www.fatsecret.co.id/kalori-gizi/umum/brokoli-dimasak-(dari-segar)",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '9001':
        meals = [
            {
                "idMeal": "9001",
                "strMeal": "Tumis Brokoli Bawang Putih",
                "strDrinkAlternate": "null",
                "strCategory": "Brokoli",
                "strArea": "Indonesia",
                "strInstructions": "Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.\r\n\r\nSpread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.\r\n\r\nAdd butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.\r\n\r\nCut into wedges and best eaten when it is warm.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=_2x5d4B9-Ko",
                "strIngredient1": "Brokoli",
                "strIngredient2": "Saus Tiram",
                "strIngredient3": "Bawang Putih",
                "strIngredient4": "Kaldu Jamur",
                "strIngredient5": "Garam",
                "strIngredient6": "Gula",
                "strIngredient7": "Lada Putih Bubuk",
                "strIngredient8": "",
                "strIngredient9": "",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 buah",
                "strMeasure2": "1 sendok makan",
                "strMeasure3": "3-4 siung",
                "strMeasure4": "1 sendok teh",
                "strMeasure5": "1 jumput",
                "strMeasure6": "1 sendok teh",
                "strMeasure7": "1/2 sendok teh",
                "strMeasure8": "",
                "strMeasure9": "",
                "strMeasure10": " ",
                "strMeasure11": " ",
                "strMeasure12": " ",
                "strMeasure13": " ",
                "strMeasure14": " ",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "https://youtu.be/_2x5d4B9-Ko?si=BKnocOMOjEo0W9NT",
                "strImageSource": "null",
                "strKal": "54",
                "strLemak": "2,69g",
                "strKarb": "6,98g",
                "strProt": "2,3g",
                "strSourceGizi": "https://www.fatsecret.co.id/kalori-gizi/umum/brokoli-dimasak-(dari-segar)",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1101':
        meals = [
            {
                "idMeal": "1101",
                "strMeal": "Daging Sapi Kecap",
                "strCategory": "Daging",
                "strArea": "Indonesia",
                "strInstructions": "Preheat the oven to 150C/300F/Gas 2.\r\nToss the beef and flour together in a bowl with some salt and black pepper.\r\nHeat a large casserole until hot, add half of the rapeseed oil and enough of the beef to just cover the bottom of the casserole.\r\nFry until browned on each side, then remove and set aside. Repeat with the remaining oil and beef.\r\nReturn the beef to the pan, add the wine and cook until the volume of liquid has reduced by half, then add the stock, onion, carrots, thyme and mustard, and season well with salt and pepper.\r\nCover with a lid and place in the oven for two hours.\r\nRemove from the oven, check the seasoning and set aside to cool. Remove the thyme.\r\nWhen the beef is cool and you're ready to assemble the pie, preheat the oven to 200C/400F/Gas 6.\r\nTransfer the beef to a pie dish, brush the rim with the beaten egg yolks and lay the pastry over the top. Brush the top of the pastry with more beaten egg.\r\nTrim the pastry so there is just enough excess to crimp the edges, then place in the oven and bake for 30 minutes, or until the pastry is golden-brown and cooked through.\r\nFor the green beans, bring a saucepan of salted water to the boil, add the beans and cook for 4-5 minutes, or until just tender.\r\nDrain and toss with the butter, then season with black pepper.\r\nTo serve, place a large spoonful of pie onto each plate with some green beans alongside.",
                "strMealThumb": "http://192.168.0.160:5000/img/daging-kecap.png",
                "strYoutube": "https://www.youtube.com/watch?v=YufaI1j_gAQ",
                "strIngredient1": "Daging sapi sengkel",
                "strIngredient2": "Daging tetelan sapi",
                "strIngredient3": "Bawang merah",
                "strIngredient4": "Bawang putih",
                "strIngredient5": "Cabe merah besar",
                "strIngredient6": "Cabe rawit",
                "strIngredient7": "Daun salam",
                "strIngredient8": "Daun jeruk",
                "strIngredient9": "Kaldu jamur",
                "strIngredient10": "Gula pasir",
                "strIngredient11": "Merica",
                "strIngredient12": "Kecap manis",
                "strIngredient13": "Saus tiram",
                "strIngredient14": "Air",
                "strIngredient15": "Cabe rawit utuh",
                "strIngredient16": "Bawang goreng",
                "strIngredient17": "Daun bawang",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "500 gram",
                "strMeasure2": "250 gram",
                "strMeasure3": "15 siung",
                "strMeasure4": "10 siung",
                "strMeasure5": "2 buah",
                "strMeasure6": "8 pcs",
                "strMeasure7": "2 lembar",
                "strMeasure8": "5 lembar",
                "strMeasure9": "2 sdt",
                "strMeasure10": "2 sdt",
                "strMeasure11": "1 sdt",
                "strMeasure12": "300g",
                "strMeasure13": "25g",
                "strMeasure14": "pinch",
                "strMeasure15": "pinch",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "https://www.bbc.co.uk/food/recipes/beef_and_mustard_pie_58002",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1102':
        meals = [
            {
                "idMeal": "1102",
                "strMeal": "Beef and Oyster pie",
                "strDrinkAlternate": "null",
                "strCategory": "Daging",
                "strArea": "British",
                "strInstructions": "Season the beef cubes with salt and black pepper. Heat a tablespoon of oil in the frying pan and fry the meat over a high heat. Do this in three batches so that you don’t overcrowd the pan, transferring the meat to a large flameproof casserole dish once it is browned all over. Add extra oil if the pan seems dry.\r\nIn the same pan, add another tablespoon of oil and cook the shallots for 4-5 minutes, then add the garlic and fry for 30 seconds. Add the bacon and fry until slightly browned. Transfer the onion and bacon mixture to the casserole dish and add the herbs.\r\nPreheat the oven to 180C/350F/Gas 4.\r\nPour the stout into the frying pan and bring to the boil, stirring to lift any stuck-on browned bits from the bottom of the pan. Pour the stout over the beef in the casserole dish and add the stock. Cover the casserole and place it in the oven for 1½-2 hours, or until the beef is tender and the sauce is reduced.\r\nSkim off any surface fat, taste and add salt and pepper if necessary, then stir in the cornflour paste. Put the casserole dish on the hob – don’t forget that it will be hot – and simmer for 1-2 minutes, stirring, until thickened. Leave to cool.\r\nIncrease the oven to 200C/400F/Gas 6. To make the pastry, put the flour and salt in a very large bowl. Grate the butter and stir it into the flour in three batches. Gradually add 325ml/11fl oz cold water – you may not need it all – and stir with a round-bladed knife until the mixture just comes together. Knead the pastry lightly into a ball on a lightly floured surface and set aside 250g/9oz for the pie lid.\r\nRoll the rest of the pastry out until about 2cm/¾in larger than the dish you’re using. Line the dish with the pastry then pile in the filling, tucking the oysters in as well. Brush the edge of the pastry with beaten egg.\r\nRoll the remaining pastry until slightly larger than your dish and gently lift over the filling, pressing the edges firmly to seal, then trim with a sharp knife. Brush with beaten egg to glaze. Put the dish on a baking tray and bake for 25-30 minutes, or until the pastry is golden-brown and the filling is bubbling.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg",
                "strTags": "Pie",
                "strYoutube": "https://www.youtube.com/watch?v=ONX74yP6JnI",
                "strIngredient1": "Beef",
                "strIngredient2": "Olive Oil",
                "strIngredient3": "Shallots",
                "strIngredient4": "Garlic",
                "strIngredient5": "Bacon",
                "strIngredient6": "Thyme",
                "strIngredient7": "Bay Leaf",
                "strIngredient8": "Stout",
                "strIngredient9": "Beef Stock",
                "strIngredient10": "Corn Flour",
                "strIngredient11": "Oysters",
                "strIngredient12": "Plain Flour",
                "strIngredient13": "Salt",
                "strIngredient14": "Butter",
                "strIngredient15": "Eggs",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "900g",
                "strMeasure2": "3 tbs",
                "strMeasure3": "3",
                "strMeasure4": "2 cloves minced",
                "strMeasure5": "125g",
                "strMeasure6": "1 tbs chopped",
                "strMeasure7": "2",
                "strMeasure8": "330ml",
                "strMeasure9": "400ml",
                "strMeasure10": "2 tbs",
                "strMeasure11": "8",
                "strMeasure12": "400g",
                "strMeasure13": "pinch",
                "strMeasure14": "250g",
                "strMeasure15": "To Glaze",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "https://www.bbc.co.uk/food/recipes/beef_and_oyster_pie_65230",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1103':
        meals = [
            {
                "idMeal": "1103",
                "strMeal": "Beef Asado",
                "strDrinkAlternate": "null",
                "strCategory": "Daging",
                "strArea": "Filipino",
                "strInstructions": "0.\tCombine beef, crushed peppercorn, soy sauce, vinegar, dried bay leaves, lemon, and tomato sauce. Mix well. Marinate beef for at least 30 minutes.\r\n1.\tPut the marinated beef in a cooking pot along with remaining marinade. Add water. Let boil.\r\n2.\tAdd Knorr Beef Cube. Stir. Cover the pot and cook for 40 minutes in low heat.\r\n3.\tTurn the beef over. Add tomato paste. Continue cooking until beef tenderizes. Set aside.\r\n4.\tHeat oil in a pan. Fry the potato until it browns. Turn over and continue frying the opposite side. Remove from the pan and place on a clean plate. Do the same with the carrots.\r\n5.\tSave 3 tablespoons of cooking oil from the pan where the potato was fried. Saute onion and garlic until onion softens.\r\n6.\tPour-in the sauce from the beef stew. Let boil. Add the beef. Cook for 2 minutes.\r\n7.\tAdd butter and let it melt. Continue cooking until the sauce reduces to half.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/pkopc31683207947.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=lNlK8DVhXXA",
                "strIngredient1": "Beef",
                "strIngredient2": "Beef Stock Concentrate",
                "strIngredient3": "Tomato Puree",
                "strIngredient4": "Water",
                "strIngredient5": "Soy Sauce",
                "strIngredient6": "White Wine Vinegar",
                "strIngredient7": "Pepper",
                "strIngredient8": "Bay Leaf",
                "strIngredient9": "Lemon",
                "strIngredient10": "Tomato Sauce",
                "strIngredient11": "Butter",
                "strIngredient12": "Olive Oil",
                "strIngredient13": "Onion",
                "strIngredient14": "Garlic",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "1.5kg",
                "strMeasure2": "1",
                "strMeasure3": "8 ounces",
                "strMeasure4": "3 cups ",
                "strMeasure5": "6 tablespoons",
                "strMeasure6": "1 tbs",
                "strMeasure7": "2 tbs",
                "strMeasure8": "4",
                "strMeasure9": "1/2 ",
                "strMeasure10": "2 tbs",
                "strMeasure11": "3 tbs",
                "strMeasure12": "1/2 cup ",
                "strMeasure13": "1 chopped",
                "strMeasure14": "4 cloves",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "https://panlasangpinoy.com/beef-asado/",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1201':
        meals = [
            {
                "idMeal": "1201",
                "strMeal": "Ayam Percik",
                "strDrinkAlternate": "null",
                "strCategory": "Ayam",
                "strArea": "Malaysian",
                "strInstructions": "In a blender, add the ingredients for the spice paste and blend until smooth.\r\nOver medium heat, pour the spice paste in a skillet or pan and fry for 10 minutes until fragrant. Add water or oil 1 tablespoon at a time if the paste becomes too dry. Don't burn the paste. Lower the fire slightly if needed.\r\nAdd the cloves, cardamom, tamarind pulp, coconut milk, water, sugar and salt. Turn the heat up and bring the mixture to boil. Turn the heat to medium low and simmer for 10 minutes. Stir occasionally. It will reduce slightly. This is the marinade/sauce, so taste and adjust seasoning if necessary. Don't worry if it's slightly bitter. It will go away when roasting.\r\nWhen the marinade/sauce has cooled, pour everything over the chicken and marinate overnight to two days.\r\nPreheat the oven to 425 F.\r\nRemove the chicken from the marinade. Spoon the marinade onto a greased (or aluminum lined) baking sheet. Lay the chicken on top of the sauce (make sure the chicken covers the sauce and the sauce isn't exposed or it'll burn) and spread the remaining marinade on the chicken. Roast for 35-45 minutes or until internal temp of the thickest part of chicken is at least 175 F.\r\nLet chicken rest for 5 minutes. Brush the chicken with some of the oil. Serve chicken with the sauce over steamed rice (or coconut rice).",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/020z181619788503.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=9ytR28QK6I8",
                "strIngredient1": "Chicken Thighs",
                "strIngredient2": "Challots",
                "strIngredient3": "Ginger",
                "strIngredient4": "Garlic Clove",
                "strIngredient5": "Cayenne Pepper",
                "strIngredient6": "Turmeric",
                "strIngredient7": "Cumin",
                "strIngredient8": "Coriander",
                "strIngredient9": "Fennel",
                "strIngredient10": "Tamarind Paste",
                "strIngredient11": "Coconut Milk",
                "strIngredient12": "Sugar",
                "strIngredient13": "Water",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "6",
                "strMeasure2": "16",
                "strMeasure3": "1 1/2 ",
                "strMeasure4": "6",
                "strMeasure5": "8",
                "strMeasure6": "2 tbs",
                "strMeasure7": "1 1/2 ",
                "strMeasure8": "1 1/2 ",
                "strMeasure9": "1 1/2 ",
                "strMeasure10": "2 tbs",
                "strMeasure11": "1 can ",
                "strMeasure12": "1 tsp ",
                "strMeasure13": "1 cup ",
                "strMeasure14": " ",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "http://www.curiousnut.com/roasted-spiced-chicken-ayam-percik/",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1202':
        meals = [
            {
                "idMeal": "1202",
                "strMeal": "Brown Stew Chicken",
                "strDrinkAlternate": "null",
                "strCategory": "Ayam",
                "strArea": "Jamaican",
                "strInstructions": "Squeeze lime over chicken and rub well. Drain off excess lime juice.\r\nCombine tomato, scallion, onion, garlic, pepper, thyme, pimento and soy sauce in a large bowl with the chicken pieces. Cover and marinate at least one hour.\r\nHeat oil in a dutch pot or large saucepan. Shake off the seasonings as you remove each piece of chicken from the marinade. Reserve the marinade for sauce.\r\nLightly brown the chicken a few pieces at a time in very hot oil. Place browned chicken pieces on a plate to rest while you brown the remaining pieces.\r\nDrain off excess oil and return the chicken to the pan. Pour the marinade over the chicken and add the carrots. Stir and cook over medium heat for 10 minutes.\r\nMix flour and coconut milk and add to stew, stirring constantly. Turn heat down to minimum and cook another 20 minutes or until tender.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/sypxpx1515365095.jpg",
                "strTags": "Stew",
                "strYoutube": "https://www.youtube.com/watch?v=_gFB1fkNhXs",
                "strIngredient1": "Chicken",
                "strIngredient2": "Tomato",
                "strIngredient3": "Onions",
                "strIngredient4": "Garlic Clove",
                "strIngredient5": "Red Pepper",
                "strIngredient6": "Carrots",
                "strIngredient7": "Lime",
                "strIngredient8": "Thyme",
                "strIngredient9": "Allspice",
                "strIngredient10": "Soy Sauce",
                "strIngredient11": "Cornstarch",
                "strIngredient12": "Coconut Milk",
                "strIngredient13": "Vegetable Oil",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "1 whole",
                "strMeasure2": "1 chopped",
                "strMeasure3": "2 chopped",
                "strMeasure4": "2 chopped",
                "strMeasure5": "1 chopped",
                "strMeasure6": "1 chopped",
                "strMeasure7": "1",
                "strMeasure8": "2 tsp",
                "strMeasure9": "1 tsp ",
                "strMeasure10": "2 tbs",
                "strMeasure11": "2 tsp",
                "strMeasure12": "2 cups ",
                "strMeasure13": "1 tbs",
                "strMeasure14": "",
                "strMeasure15": "",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "http://www.geniuskitchen.com/recipe/authentic-jamaican-brown-stew-chicken-347996",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1203':
        meals = [
            {
                "idMeal": "1203",
                "strMeal": "Chick-Fil-A Sandwich",
                "strDrinkAlternate": "null",
                "strCategory": "Ayam",
                "strArea": "American",
                "strInstructions": "Wrap the chicken loosely between plastic wrap and pound gently with the flat side of a meat tenderizer until about 1/2 inch thick all around.\r\nCut into two pieces, as even as possible.\r\nMarinate in the pickle juice for 30 minutes to one hour (add a teaspoon of Tabasco sauce now for a spicy sandwich).\r\nBeat the egg with the milk in a bowl.\r\nCombine the flour, sugar, and spices in another bowl.\r\nDip the chicken pieces each into the egg on both sides, then coat in flour on both sides.\r\nHeat the oil in a skillet (1/2 inch deep) to about 345-350.\r\nFry each cutlet for 2 minutes on each side, or until golden and cooked through.\r\nBlot on paper and serve on toasted buns with pickle slices.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=1WDesu7bUDM",
                "strIngredient1": "Chicken Breast",
                "strIngredient2": "Pickle Juice",
                "strIngredient3": "Egg",
                "strIngredient4": "Milk",
                "strIngredient5": "Flour",
                "strIngredient6": "Icing Sugar",
                "strIngredient7": "Paprika",
                "strIngredient8": "Salt",
                "strIngredient9": "Black Pepper",
                "strIngredient10": "Garlic Powder",
                "strIngredient11": "Celery Salt",
                "strIngredient12": "Cayenne Pepper",
                "strIngredient13": "Olive Oil",
                "strIngredient14": "Sesame Seed Burger Buns",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "1",
                "strMeasure2": "1/4 cup",
                "strMeasure3": "1",
                "strMeasure4": "1/4 cup",
                "strMeasure5": "1/2 cup ",
                "strMeasure6": "1 tbs",
                "strMeasure7": "1/2 tsp",
                "strMeasure8": "1/2 tsp",
                "strMeasure9": "1/4 tsp",
                "strMeasure10": "1/4 tsp",
                "strMeasure11": "1/4 tsp",
                "strMeasure12": "1/2 tsp",
                "strMeasure13": "1 cup ",
                "strMeasure14": "1",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "https://hilahcooking.com/chick-fil-a-copycat/",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1301':
        meals = [
            {
                "idMeal": "1301",
                "strMeal": "Baked salmon with fennel & tomatoes",
                "strDrinkAlternate": "null",
                "strCategory": "Seafood",
                "strArea": "British",
                "strInstructions": "Heat oven to 180C/fan 160C/gas 4. Trim the fronds from the fennel and set aside. Cut the fennel bulbs in half, then cut each half into 3 wedges. Cook in boiling salted water for 10 mins, then drain well. Chop the fennel fronds roughly, then mix with the parsley and lemon zest.\r\n\r\nSpread the drained fennel over a shallow ovenproof dish, then add the tomatoes. Drizzle with olive oil, then bake for 10 mins. Nestle the salmon among the veg, sprinkle with lemon juice, then bake 15 mins more until the fish is just cooked. Scatter over the parsley and serve.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/1548772327.jpg",
                "strTags": "Paleo,Keto,HighFat,Baking,LowCarbs",
                "strYoutube": "https://www.youtube.com/watch?v=xvPR2Tfw5k0",
                "strIngredient1": "Fennel",
                "strIngredient2": "Parsley",
                "strIngredient3": "Lemon",
                "strIngredient4": "Cherry Tomatoes",
                "strIngredient5": "Olive Oil",
                "strIngredient6": "Salmon",
                "strIngredient7": "Black Olives",
                "strIngredient8": "",
                "strIngredient9": "",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 medium",
                "strMeasure2": "2 tbs chopped",
                "strMeasure3": "Juice of 1",
                "strMeasure4": "175g",
                "strMeasure5": "1 tbs",
                "strMeasure6": "350g",
                "strMeasure7": "to serve",
                "strMeasure8": "",
                "strMeasure9": "",
                "strMeasure10": "",
                "strMeasure11": "",
                "strMeasure12": "",
                "strMeasure13": "",
                "strMeasure14": "",
                "strMeasure15": "",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "https://www.bbcgoodfood.com/recipes/7745/baked-salmon-with-fennel-and-tomatoes",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1302':
        meals = [
            {
                "idMeal": "1302",
                "strMeal": "Cajun spiced fish tacos",
                "strDrinkAlternate": "null",
                "strCategory": "Seafood",
                "strArea": "Mexican",
                "strInstructions": "Cooking in a cajun spice and cayenne pepper marinade makes this fish super succulent and flavoursome. Top with a zesty dressing and serve in a tortilla for a quick, fuss-free main that's delightfully summery.\r\n\r\nOn a large plate, mix the cajun spice and cayenne pepper with a little seasoning and use to coat the fish all over.\r\n\r\nHeat a little oil in a frying pan, add in the fish and cook over a medium heat until golden. Reduce the heat and continue frying until the fish is cooked through, about 10 minutes. Cook in batches if you don’t have enough room in the pan.\r\n\r\nMeanwhile, prepare the dressing by combining all the ingredients with a little seasoning.\r\nSoften the tortillas by heating in the microwave for 5-10 seconds. Pile high with the avocado, lettuce and spring onion, add a spoonful of salsa, top with large flakes of fish and drizzle over the dressing.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg",
                "strTags": "Spicy,Fish",
                "strYoutube": "https://www.youtube.com/watch?v=N4EdUt0Ou48",
                "strIngredient1": "cajun",
                "strIngredient2": "cayenne pepper",
                "strIngredient3": "white fish",
                "strIngredient4": "vegetable oil",
                "strIngredient5": "flour tortilla",
                "strIngredient6": "avocado",
                "strIngredient7": "little gem lettuce",
                "strIngredient8": "spring onion",
                "strIngredient9": "salsa",
                "strIngredient10": "sour cream",
                "strIngredient11": "lemon",
                "strIngredient12": "garlic",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 tbsp",
                "strMeasure2": "1 tsp",
                "strMeasure3": "4 fillets",
                "strMeasure4": "1 tsp",
                "strMeasure5": "8",
                "strMeasure6": "1 sliced",
                "strMeasure7": "2 shredded",
                "strMeasure8": "4 shredded",
                "strMeasure9": "1 x 300ml",
                "strMeasure10": "1 pot",
                "strMeasure11": "1",
                "strMeasure12": "1 clove finely chopped",
                "strMeasure13": "",
                "strMeasure14": "",
                "strMeasure15": "",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "https://realfood.tesco.com/recipes/cajun-spiced-fish-tacos.html",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1303':
        meals = [
            {
                "idMeal": "1303",
                "strMeal": "Escovitch Fish",
                "strDrinkAlternate": "null",
                "strCategory": "Seafood",
                "strArea": "Jamaican",
                "strInstructions": "Rinse fish; rub with lemon or lime, seasoned with salt and pepper or use your favorite seasoning. I used creole seasoning. Set aside or place in the oven to keep it warm until sauce is ready.\r\n\r\nIn large skillet heat oil over medium heat, until hot, add the fish, cook each side- for about 5-7 minutes until cooked through and crispy on both sides. Remove fish and set aside. Drain oil and leave about 2-3 tablespoons of oil\r\nAdd, bay leave, garlic and ginger, stir-fry for about a minute making sure the garlic does not burn\r\nThen add onion, bell peppers, thyme, scotch bonnet, sugar, all spice-continue stirring for about 2-3 minutes. Add vinegar, mix an adjust salt and pepper according to preference. Let it simmer for about 2 more minutes. \r\n\r\nDiscard bay leave, thyme spring and serve over fish with a side of this bammy. You may make the sauce about 2 days in advance.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/1520084413.jpg",
                "strTags": "Seafood,Spicy,Speciality,Easter",
                "strYoutube": "https://www.youtube.com/watch?v=nF6DOtGE6k8",
                "strIngredient1": "Red Snapper",
                "strIngredient2": "Vegetable Oil",
                "strIngredient3": "Garlic",
                "strIngredient4": "Ginger",
                "strIngredient5": "Thyme",
                "strIngredient6": "Bay Leaf",
                "strIngredient7": "Red Pepper",
                "strIngredient8": "Yellow Pepper",
                "strIngredient9": "Onion",
                "strIngredient10": "Carrots",
                "strIngredient11": "Sugar",
                "strIngredient12": "Allspice",
                "strIngredient13": "Worcestershire Sauce",
                "strIngredient14": "Scotch Bonnet",
                "strIngredient15": "Lime",
                "strIngredient16": "Malt Vinegar",
                "strIngredient17": "Pepper",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 Pounds",
                "strMeasure2": "1/2 cup ",
                "strMeasure3": "1 clove peeled crushed",
                "strMeasure4": "1/2 tsp",
                "strMeasure5": "2 sprigs",
                "strMeasure6": "1",
                "strMeasure7": "0.5",
                "strMeasure8": "0.5",
                "strMeasure9": "1 sliced",
                "strMeasure10": "1 chopped",
                "strMeasure11": "1 tbs",
                "strMeasure12": "1/2 tsp",
                "strMeasure13": "1 tsp ",
                "strMeasure14": "1",
                "strMeasure15": "1",
                "strMeasure16": "3/4 cup ",
                "strMeasure17": "pinch",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "https://www.africanbites.com/jamaican-escovitched-fish/",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1401':
        meals = [
            {
                "idMeal": "1401",
                "strMeal": "Bubur Manado (Tinutuan)",
                "strCategory": "Sayuran",
                "strArea": "Manado",
                "strInstructions": "1.Didihkan air secukupnya\n\n2.Tambahkan Serai\n\n3.Tambahkan beras yang sudah dicuci\n\n4.Tambahkan garam secukupnya\n\n5.Tambahkan Ubi\n\n6.Tambahkan Jagung\n\n7.Tambahkan Kangkung\n\n8.Tambahkan Bayam\n\nKarbo: 61.67 gram\nLemak: 7.63 gram\nProtein: 10.51 gram",
                "strMealThumb": "http://192.168.0.160:5000/img/bubur-manado.jpeg",
                "strKal":"349",
                "strMenit":"7",
                "strPorsi":"1",
                "strYoutube": "https://www.youtube.com/watch?v=86oqI5vjIxo",
                "strIngredient1": "Beras",
                "strIngredient2": "Kangkung",
                "strIngredient3": "Bayam",
                "strIngredient4": "Jagung",
                "strIngredient5": "Serai",
                "strIngredient6": "Ubi",
                "strIngredient7": "",
                "strIngredient8": "",
                "strIngredient9": "",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "250 gram",
                "strMeasure2": "100 gram",
                "strMeasure3": "100 gram",
                "strMeasure4": "1 buah",
                "strMeasure5": "1 batang",
                "strMeasure6": "Potong Dadu",
                "strMeasure7": "",
                "strMeasure8": "",
                "strMeasure9": "",
                "strMeasure10": "",
                "strMeasure11": "",
                "strMeasure12": "",
                "strMeasure13": "",
                "strMeasure14": "",
                "strMeasure15": "",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1402':
        meals = [
            {
                "idMeal": "1402",
                "strMeal": "Cap Cay",
                "strCategory": "Sayuran",
                "strArea": "Indonesia",
                "strInstructions": "1.Didihkan air secukupnya\n\n2.Tambahkan Serai\n\n3.Tambahkan beras yang sudah dicuci\n\n4.Tambahkan garam secukupnya\n\n5.Tambahkan Ubi\n\n6.Tambahkan Jagung\n\n7.Tambahkan Kangkung\n\n8.Tambahkan Bayam\n\nKarbo: 61.67 gram\nLemak: 7.63 gram\nProtein: 10.51 gram",
                "strMealThumb": "http://192.168.0.160:5000/img/capcay.jpeg",
                "strKal":"349",
                "strMenit":"7",
                "strPorsi":"1",
                "strYoutube": "https://www.youtube.com/watch?v=gurVqGFI3NU",
                "strIngredient1": "Brokoli",
                "strIngredient2": "Wortel ukuran kecil",
                "strIngredient3": "Jamur Shimeji",
                "strIngredient4": "Kol",
                "strIngredient5": "Bakso",
                "strIngredient6": "Bawang Putih cincang",
                "strIngredient7": "Jahe",
                "strIngredient8": "Daun Bawang",
                "strIngredient9": "Chicken Powder",
                "strIngredient10": "Saus Tiram",
                "strIngredient11": "Kecap Asin",
                "strIngredient12": "Kecap Ikan",
                "strIngredient13": "Minyak Wijen",
                "strIngredient14": "Gula",
                "strIngredient15": "Lada Putih",
                "strIngredient16": "Air",
                "strIngredient17": "Air + 1 sdm Tepung Tapioka / Sagu",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "1",
                "strMeasure2": "1",
                "strMeasure3": "1 bks",
                "strMeasure4": "¼",
                "strMeasure5": "8 pcs",
                "strMeasure6": "4",
                "strMeasure7": "2 iris",
                "strMeasure8": "1 batang",
                "strMeasure9": "½ sdm",
                "strMeasure10": "3 sdm",
                "strMeasure11": "1 sdm",
                "strMeasure12": "1 sdm",
                "strMeasure13": "2 sdt",
                "strMeasure14": "3 sdm",
                "strMeasure15": "1 sdt",
                "strMeasure16": "350 ml",
                "strMeasure17": "20 ml",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1501':
        meals = [
            {
                "idMeal": "1501",
                "strMeal": "Bread omelette",
                "strDrinkAlternate": "null",
                "strCategory": "Sarapan",
                "strArea": "Indian",
                "strInstructions": "Make and enjoy",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/hqaejl1695738653.jpg",
                "strTags": "null",
                "strYoutube": "",
                "strIngredient1": "Bread",
                "strIngredient2": "Egg",
                "strIngredient3": "Salt",
                "strIngredient4": "",
                "strIngredient5": "",
                "strIngredient6": "",
                "strIngredient7": "",
                "strIngredient8": "",
                "strIngredient9": "",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2",
                "strMeasure2": "2",
                "strMeasure3": "0.5",
                "strMeasure4": " ",
                "strMeasure5": " ",
                "strMeasure6": " ",
                "strMeasure7": " ",
                "strMeasure8": " ",
                "strMeasure9": " ",
                "strMeasure10": " ",
                "strMeasure11": " ",
                "strMeasure12": " ",
                "strMeasure13": " ",
                "strMeasure14": " ",
                "strMeasure15": " ",
                "strMeasure16": " ",
                "strMeasure17": " ",
                "strMeasure18": " ",
                "strMeasure19": " ",
                "strMeasure20": " ",
                "strSource": "",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == '1601':
        meals = [
            {
                "idMeal": "1601",
                "strMeal": "Broccoli & Stilton soup",
                "strDrinkAlternate": "null",
                "strCategory": "Pembuka",
                "strArea": "British",
                "strInstructions": "Heat the rapeseed oil in a large saucepan and then add the onions. Cook on a medium heat until soft. Add a splash of water if the onions start to catch.\r\n\r\nAdd the celery, leek, potato and a knob of butter. Stir until melted, then cover with a lid. Allow to sweat for 5 minutes. Remove the lid.\r\n\r\nPour in the stock and add any chunky bits of broccoli stalk. Cook for 10 – 15 minutes until all the vegetables are soft.\r\n\r\nAdd the rest of the broccoli and cook for a further 5 minutes. Carefully transfer to a blender and blitz until smooth. Stir in the stilton, allowing a few lumps to remain. Season with black pepper and serve.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/tvvxpv1511191952.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=_HgVLpmNxTY",
                "strIngredient1": "Rapeseed Oil",
                "strIngredient2": "Onion",
                "strIngredient3": "Celery",
                "strIngredient4": "Leek",
                "strIngredient5": "Potatoes",
                "strIngredient6": "Butter",
                "strIngredient7": "Vegetable Stock",
                "strIngredient8": "Broccoli",
                "strIngredient9": "Stilton Cheese",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 tblsp ",
                "strMeasure2": "1 finely chopped ",
                "strMeasure3": "1",
                "strMeasure4": "1 sliced",
                "strMeasure5": "1 medium",
                "strMeasure6": "1 knob",
                "strMeasure7": "1 litre hot",
                "strMeasure8": "1 Head chopped",
                "strMeasure9": "140g",
                "strMeasure10": "",
                "strMeasure11": "",
                "strMeasure12": "",
                "strMeasure13": "",
                "strMeasure14": "",
                "strMeasure15": "",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "https://www.bbcgoodfood.com/recipes/1940679/broccoli-and-stilton-soup",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == 'a01':
        meals = [
            {
                "idMeal": "a01",
                "strMeal": "Broccoli & Stilton soup",
                "strDrinkAlternate": "null",
                "strCategory": "Pembuka",
                "strArea": "British",
                "strInstructions": "Heat the rapeseed oil in a large saucepan and then add the onions. Cook on a medium heat until soft. Add a splash of water if the onions start to catch.\r\n\r\nAdd the celery, leek, potato and a knob of butter. Stir until melted, then cover with a lid. Allow to sweat for 5 minutes. Remove the lid.\r\n\r\nPour in the stock and add any chunky bits of broccoli stalk. Cook for 10 – 15 minutes until all the vegetables are soft.\r\n\r\nAdd the rest of the broccoli and cook for a further 5 minutes. Carefully transfer to a blender and blitz until smooth. Stir in the stilton, allowing a few lumps to remain. Season with black pepper and serve.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/tvvxpv1511191952.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=_HgVLpmNxTY",
                "strIngredient1": "Rapeseed Oil",
                "strIngredient2": "Onion",
                "strIngredient3": "Celery",
                "strIngredient4": "Leek",
                "strIngredient5": "Potatoes",
                "strIngredient6": "Butter",
                "strIngredient7": "Vegetable Stock",
                "strIngredient8": "Broccoli",
                "strIngredient9": "Stilton Cheese",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 tblsp ",
                "strMeasure2": "1 finely chopped ",
                "strMeasure3": "1",
                "strMeasure4": "1 sliced",
                "strMeasure5": "1 medium",
                "strMeasure6": "1 knob",
                "strMeasure7": "1 litre hot",
                "strMeasure8": "1 Head chopped",
                "strMeasure9": "140g",
                "strMeasure10": "",
                "strMeasure11": "",
                "strMeasure12": "",
                "strMeasure13": "",
                "strMeasure14": "",
                "strMeasure15": "",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "https://www.bbcgoodfood.com/recipes/1940679/broccoli-and-stilton-soup",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    elif id == 'b01':
        meals = [
            {
                "idMeal": "b01",
                "strMeal": "Broccoli & Stilton soup",
                "strDrinkAlternate": "null",
                "strCategory": "Pembuka",
                "strArea": "British",
                "strInstructions": "Heat the rapeseed oil in a large saucepan and then add the onions. Cook on a medium heat until soft. Add a splash of water if the onions start to catch.\r\n\r\nAdd the celery, leek, potato and a knob of butter. Stir until melted, then cover with a lid. Allow to sweat for 5 minutes. Remove the lid.\r\n\r\nPour in the stock and add any chunky bits of broccoli stalk. Cook for 10 – 15 minutes until all the vegetables are soft.\r\n\r\nAdd the rest of the broccoli and cook for a further 5 minutes. Carefully transfer to a blender and blitz until smooth. Stir in the stilton, allowing a few lumps to remain. Season with black pepper and serve.",
                "strMealThumb": "https://www.themealdb.com/images/media/meals/tvvxpv1511191952.jpg",
                "strTags": "null",
                "strYoutube": "https://www.youtube.com/watch?v=_HgVLpmNxTY",
                "strIngredient1": "Rapeseed Oil",
                "strIngredient2": "Onion",
                "strIngredient3": "Celery",
                "strIngredient4": "Leek",
                "strIngredient5": "Potatoes",
                "strIngredient6": "Butter",
                "strIngredient7": "Vegetable Stock",
                "strIngredient8": "Broccoli",
                "strIngredient9": "Stilton Cheese",
                "strIngredient10": "",
                "strIngredient11": "",
                "strIngredient12": "",
                "strIngredient13": "",
                "strIngredient14": "",
                "strIngredient15": "",
                "strIngredient16": "",
                "strIngredient17": "",
                "strIngredient18": "",
                "strIngredient19": "",
                "strIngredient20": "",
                "strMeasure1": "2 tblsp ",
                "strMeasure2": "1 finely chopped ",
                "strMeasure3": "1",
                "strMeasure4": "1 sliced",
                "strMeasure5": "1 medium",
                "strMeasure6": "1 knob",
                "strMeasure7": "1 litre hot",
                "strMeasure8": "1 Head chopped",
                "strMeasure9": "140g",
                "strMeasure10": "",
                "strMeasure11": "",
                "strMeasure12": "",
                "strMeasure13": "",
                "strMeasure14": "",
                "strMeasure15": "",
                "strMeasure16": "",
                "strMeasure17": "",
                "strMeasure18": "",
                "strMeasure19": "",
                "strMeasure20": "",
                "strSource": "https://www.bbcgoodfood.com/recipes/1940679/broccoli-and-stilton-soup",
                "strImageSource": "null",
                "strCreativeCommonsConfirmed": "null",
                "dateModified": "null"
            }
        ]
    else:
        return jsonify({"message": "Recipe not found"})

    return jsonify({"meals": meals})
